version: '3'

services:
  core:
    container_name: core
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_NAME: core
    restart: always
    ports:
      - 3001:3000
    networks:
      - app_network

  user-gateway:
    container_name: user-gateway
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_NAME: user-gateway
    restart: always
    ports:
      - 3002:3000
    networks:
      - app_network

  notification:
    container_name: notification
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_NAME: notification
    restart: always
    ports:
      - 3003:3000
    networks:
      - app_network

  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./.cert:/etc/caddy/cert:ro
    depends_on:
      - core
      - user-gateway
      - notification
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
